### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by heavygale** [caddy-dns/netcup#7]
The Build in the web-downloader is failing:
https://caddyserver.com/download?package=github.com%2Fcaddy-dns%2Fnetcup

Adding the module via command line also fails:
```
# caddy add-package github.com/caddy-dns/netcup
2024/06/08 21:38:46.258	INFO	this executable will be replaced	{"path": "/usr/bin/caddy"}
2024/06/08 21:38:46.258	INFO	requesting build	{"os": "linux", "arch": "amd64", "packages": ["github.com/caddy-dns/netcup"]}
Error: download failed: download failed: HTTP 400: unable to fulfill download request (id=89ff3b75-78e1-4fcc-b9e2-f0d161c44534)
```

Should I try compiling it using xcaddy as this might be an error in the downloader or is there something wrong with the module itself?

**Comment by hypervtechnics** [comment]
I am building using `xcaddy` and get this error during the build:

```
62.54 2024/06/15 12:58:19 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /usr/bin/caddy -ldflags -w -s -trimpath -tags nobadger
73.68 # github.com/libdns/netcup
73.68 /go/pkg/mod/github.com/libdns/netcup@v0.1.0/util.go:27:14: cannot use record.Priority (variable of type int) as uint value in struct literal
73.68 /go/pkg/mod/github.com/libdns/netcup@v0.1.0/util.go:43:17: cannot use record.Priority (variable of type uint) as int value in struct literal
98.46 2024/06/15 12:58:55 [INFO] Skipping cleanup as requested; leaving folder intact: /tmp/buildenv_2024-06-15-1257.275866987
98.46 2024/06/15 12:58:55 [FATAL] exit status 1
```

**Comment by hypervtechnics** [comment]
I see a fix was merged in https://github.com/libdns/netcup/pull/1, checking this out and running go build also succeeds.

In the logs of the build of xcaddy I also see: 

```
30.95 2024/06/15 13:00:23 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/netcup github.com/caddyserver/caddy/v2@v2.8.4
31.17 go: downloading github.com/caddy-dns/netcup v0.1.0
31.24 go: downloading github.com/libdns/netcup v0.1.0
31.52 go: added github.com/caddy-dns/netcup v0.1.0
31.52 go: added github.com/libdns/netcup v0.1.0
```

This probably says that only the (very old) v0.1.0 tag gets downloaded and not the version in main with the fix in it. So I used this xcaddy parameter: `--with github.com/caddy-dns/netcup@a811da94403509715bd149669b07544706fd6d46`.

This fixed the build and can be used as a workaround until the maintainers update the git tag.

**Comment by CameronMunroe** [comment]
default build is still broken, we likely need to tag a new release.

**Comment by heavygale** [comment]
Who could you help us out here? @Monviech maybe?

**Comment by KnudH** [comment]
You need help with doing the release or how can we help?

**Comment by heavygale** [comment]
The new libdns version has been added to this repo (https://github.com/caddy-dns/netcup/pull/6/) but there's no new version tag, so "caddy add-package github.com/caddy-dns/netcup" still tries to install the old code. I don't know how to tag a new version, so yes I think that's what we need help with.

**Comment by mholt** [comment]
I've just cleared the build cache. Hopefully that helps :+1:

**Comment by heavygale** [comment]
The website still fails to provide caddy with the netcup dns-plugin: 
https://caddyserver.com/download?package=github.com%2Fcaddy-dns%2Fnetcup
![grafik](https://github.com/user-attachments/assets/d295fe8f-8537-47ad-b1d0-76efa3a74df6)

Same result via commandline:
```
# caddy add-package github.com/caddy-dns/netcup
2024/10/30 15:03:46.804	INFO	this executable will be replaced	{"path": "/usr/bin/caddy"}
2024/10/30 15:03:46.804	INFO	requesting build	{"os": "linux", "arch": "amd64", "packages": ["github.com/caddyserver/transform-encoder", "github.com/caddy-dns/netcup"]}
Error: download failed: download failed: HTTP 400: unable to fulfill download request (id=cc04bcde-0240-4eb9-83ac-ed1552ade5ee)
```

What code version does the build process use?
If it looks for the latest tag, the v0.1.0 is from 2022-01-12

**Comment by mholt** [comment]
Keep in mind that the latest tag will be used for the build, so a new tag should be created.

As a workaround until then, you can type `main` into the "version" input box to build the latest commit and it will work.

**Comment by heavygale** [comment]
`caddy add-package github.com/caddy-dns/netcup@main`
Thanks, that worked 👍

**Comment by KnudH** [comment]
I think you can just use the default git-tags (https://git-scm.com/book/en/v2/Git-Basics-Tagging) and then push the tag to the server, and you are fine, or am I completely on the wrong track?

**Comment by mholt** [comment]
That's correct. A standard git tag will do it 👍

**Comment by heavygale** [comment]
I would like to do that, but unfortunately I don't have write access to this repository.

**Comment by mholt** [comment]
@heavygale Fixed -- sent you an invite to collab on it. Thanks!

**Comment by heavygale** [comment]
Thank you! I've created a new tag.
Build and download via the website and `caddy add-package` now works again (without manually specifying a version). 👍
